media:
  input: Photos
  output: /photos

content:
  - name: projets
    label: Projets
    type: collection
    path: projets
    fields:
      - name: Categorie
        type: select
        options:
        values: [Architecture, Instalations, A-propos]
      - name: Titre
        label: Titre
        type: string
      - name: Titre-anglais
        label: Titre-anglais
        type: string
      - name: Description
        label: Description
        type: rich-text
      - name: Description-anglais
        label: Description-anglais
        type: rich-text
      - name: Annee
        label: Annee
        type: string
      - name: Lieu
        label: Lieu
        type: string
      - name: Photographe
        label: Photographe
        type: string
      - name: Photos
        label: Photos
        type: object
        list: true
        fields:
          - name: Photo
            label: Photo
            type: image
            list: true
          - name: Carrousel
            type: boolean
            default: false
